#ifndef _BOUNDARYCONDITION_H
#define _BOUNDARYCONDITION_H

extern double **First0;
extern double **First1;
extern double **First2;
extern double **First3;
extern double **First4;
extern double **First5;
extern double **First6;
extern double **First7;
extern double **First8;
extern double **First9;
extern double **First10;
extern double **First11;
extern double **First12;
extern double **First13;
extern double **First14;
extern double **First15;
extern double **First16;
extern double **First17;
extern double **First18;
extern double **FirstRho2;
extern double **FirstPressure2;
extern double **FirstFx;
extern double **FirstFy;
extern double **FirstFz;

extern double **Last0;
extern double **Last1;
extern double **Last2;
extern double **Last3;
extern double **Last4;
extern double **Last5;
extern double **Last6;
extern double **Last7;
extern double **Last8;
extern double **Last9;
extern double **Last10;
extern double **Last11;
extern double **Last12;
extern double **Last13;
extern double **Last14;
extern double **Last15;
extern double **Last16;
extern double **Last17;
extern double **Last18;
extern double **LastFx;
extern double **LastFy;
extern double **LastFz;
extern double **LastRho;
extern double **LastUx;
extern double **LastUy;
extern double **LastUz;
extern double **LastPressure1;
extern double **LastPressure2;

extern double **Last0Concentration;
extern double **Last1Concentration;
extern double **Last2Concentration;
extern double **Last3Concentration;
extern double **Last4Concentration;
extern double **Last5Concentration;
extern double **Last6Concentration;
extern double **Last7Concentration;
extern double **Last8Concentration;
extern double **Last9Concentration;
extern double **Last10Concentration;
extern double **Last11Concentration;
extern double **Last12Concentration;
extern double **Last13Concentration;
extern double **Last14Concentration;
extern double **Last15Concentration;
extern double **Last16Concentration;
extern double **Last17Concentration;
extern double **Last18Concentration;

extern double **First0Ghost;
extern double **First1Ghost;
extern double **First2Ghost;
extern double **First3Ghost;
extern double **First4Ghost;
extern double **First5Ghost;
extern double **First6Ghost;
extern double **First7Ghost;
extern double **First8Ghost;
extern double **First9Ghost;
extern double **First10Ghost;
extern double **First11Ghost;
extern double **First12Ghost;
extern double **First13Ghost;
extern double **First14Ghost;
extern double **First15Ghost;
extern double **First16Ghost;
extern double **First17Ghost;
extern double **First18Ghost;

extern double **Last0Ghost;
extern double **Last1Ghost;
extern double **Last2Ghost;
extern double **Last3Ghost;
extern double **Last4Ghost;
extern double **Last5Ghost;
extern double **Last6Ghost;
extern double **Last7Ghost;
extern double **Last8Ghost;
extern double **Last9Ghost;
extern double **Last10Ghost;
extern double **Last11Ghost;
extern double **Last12Ghost;
extern double **Last13Ghost;
extern double **Last14Ghost;
extern double **Last15Ghost;
extern double **Last16Ghost;
extern double **Last17Ghost;
extern double **Last18Ghost;

extern void FirstlineArrangeTwoPhase(int n, int q);
extern void LastlineArrangeTwoPhase(int m, int n);
extern void LastlineArrangeConcentration(int n, int q);
extern void FirstlineArrangeVelocityGhost(int n, int q);
extern void LastlineArrangeVelocityGhost(int n, int q);
extern double lengthSurfacelineCalculation(int layerNumber, int initial, int m, int finish, int n, double ***uz);
extern void SurfacelineSave(int layerNumber1,int m,int n,int q,double **Save0,double **Save1,double **Save2,double **Save3,double **Save4,double **Save5,double **Save6,
	double **Save7,double **Save8,double **Save9,double **Save10,double **Save11,double **Save12,double **Save13,double **Save14,double **Save15,double **Save16,double **Save17,double **Save18,double **SaveRho,double **SaveUx,double **SaveUy,double **SaveUz,double **SavePressure1,double **SavePressure2,
	double ***In0,double ***In1,double ***In2,double ***In3,double ***In4,double ***In5,double ***In6,double ***In7,double ***In8,double ***In9,
	double ***In10,double ***In11,double ***In12,double ***In13,double ***In14,double ***In15,double ***In16,double ***In17,double ***In18,double ***Rho,double ***ux,double ***uy,double ***uz,double ***pressure);
extern void LastsurfaceLineMemoryFreeTwoPhase(int m);
extern void FirstsurfaceLineMemoryFreeTwoPhase(int n);
extern void surfaceLineMemoryFreeConcentration(int n);
extern void surfaceLineMemoryFreeVelocityGhost(int n);
extern void lengthFirstConstantVelocityBoundaryTwoPhase(int nInitial,int n,int qInitial,int q,double InletUx,double InletUy,double InletUz,double solid,double b, double R, double T, double a);
extern void HeightFirstConstantVelocityBoundaryTwoPhase(int mInitial,int m,int nInitial,int n,double InletSideUz,double InletSideUx,double InletSideUy,double solid,double b, double R, double T, double a);
extern void HeightFirstConstantPressureBoundaryTwoPhase(int mInitial,int m,int nInitial,int n,double InletDensity,double InletSideUx,double InletSideUy,double solid,double b, double R, double T, double a);
extern void HeightLastConstantVelocityBoundaryTwoPhase(int q,int mInitial,int m,int nInitial,int n,double InletSideUz,double InletSideUx,double InletSideUy,double solid,double b, double R, double T, double a);
extern void HeightLastConstantPressureBoundaryTwoPhase(int q,int mInitial,int m,int nInitial,int n,double outPutDensity,double InletSideUx,double InletSideUy,double solid,double b, double R, double T, double a);
extern void HeightLastVelocityConvectiveTwoPhase(int q,int mInitial,int m,int nInitial,int n,double uzAV,double solid,double b, double R, double T, double a);
extern void HeightLastNeumannVelocityTwoPhase(int q,int mInitial,int m,int nInitial,int n,double solid);
extern void lengthFirstForceVelocityConvectiveTwoPhase(int nInitial,int n,int qInitial,int q,double uxAV,double G);
extern void lengthFirstVelocityConvectiveTwoPhase(int nInitial,int n,int qInitial,int q,double uxAV,double solid,double b, double R, double T, double a);
extern void lengthFirstVelocityConvectiveGhost(int nInitial,int n,int qInitial,int q,double uxAV,double solid,double gasCritical);
extern void lengthFirstNeumannInletTwoPhase(int nInitial,int n,int qInitial,int q,double solid);
extern void lengthFirstConstantPressureTwoPhase(int nInitial,int n,int qInitial,int q,double rhoConstant,double InletUy,double InletUz,double solid,double b, double R, double T, double a);
extern void lengthForceSave(int layerNumber1,int n,int q,double **SaveFx,double **SaveFy,double **SaveFz,double ***Fx,double ***Fy,double ***Fz,double G);
extern void lengthLastForceVelocityConvectiveTwoPhase(int m,int nInitial,int n,int qInitial,int q,double uxAV,double G);
extern void lengthLastVelocityConvectiveTwoPhase(int m,int nInitial,int n,int qInitial,int q,double uxAV,double solid,double b, double R, double T, double a);
extern void lengthLastVelocityConvectiveGhost(int m,int nInitial,int n,int qInitial,int q,double uxAV,double solid,double gasCritical);
extern void lengthLastNeumannBoundaryTwoPhase(int m,int nInitial,int n,int qInitial,int q,double solid);
extern void lengthLastConstantVelocityBoundaryTwoPhase(int m,int nInitial,int n,int qInitial,int q,double InletUx,double InletUy,double InletUz,double solid,double b,double R,double T,double a);
extern void lengthLastConstantPressureBoundaryTwoPhase(int m,int nInitial,int n,int qInitial,int q,double rhoConstant,double InletUy,double InletUz,double solid,double b,double R,double T,double a);
extern void lengthFirstDirichletConcentration(int Width,int Height,double InletConcentration,double gasCritical);
extern void lengthLastConvectiveConcentration(int Length,int nInitial,int Width,int qInitial,int Height,double uxAV,double gasCritical);
extern void lengthLastNeumannConcentration(int Length,int Width,int Height);
extern void gasLiquidBoundaryConcentration(int m, int n, int q, double gasCritical);
extern void gasLiquidBoundaryConcentrationD3Q7(int m, int n, int q, double gasCritical);
extern void gasLiquidBoundaryConcentrationD3Q15(int m, int n, int q, double gasCritical);
extern void gasLiquidBoundaryConcentrationFirst(int m, int n, int q, double gasCritical);
extern void gasLiquidBoundaryConcentrationFirstD3Q7(int m, int n, int q, double gasCritical);
extern void gasLiquidBoundaryConcentrationSecond(int m, int n, int q, double gasCritical);
extern void gasLiquidBoundaryConcentrationSecondD3Q7(int m, int n, int q, double gasCritical);
extern void gasLiquidBoundaryVelocityGhost(int m, int n, int q, double gasCritical);
extern void gasLiquidBoundaryElectrolytePotential(int m, int n, int q, double gasCritical);
extern void gasLiquidBoundaryElectrolytePotentialD3Q7(int m, int n, int q, double gasCritical);
extern void lengthLastNeumannVelocityGhost(int Length,int Width,int Height);
extern void lengthFirstNeumannVelocityGhost(int Length,int Width,int Height);
extern void widthFirstNeumannVelocityGhost(int Length,int Width,int Height);
extern void widthFirstNeumannConcentration(int Length,int Width,int Height);
extern void widthFirstNeumannConcentrationElectrode(int Length,int Width,int Height);
extern void widthFirstNeumannConcentrationSecond(int Length,int Width,int Height);
extern void HeightLastConstantVelocityBoundaryGhost(int q,int mInitial,int m,int nInitial,int n,double InletSideUz,double InletSideUx,double InletSideUy,double solid,double b, double R, double T, double a);
extern void WidthLastConstantVelocityBoundaryGhost(int q, int mInitial, int m, int nInitial, int n, double InletSideUz, double InletSideUx, double InletSideUy, double solid);
extern void WidthLastConstantPressureBoundaryGhost(int q, int mInitial, int m, int nInitial, int n, double outPutDensity, double InletSideUx, double InletSideUz, double solid, double gasCritical);
extern void HeightFirstConstantVelocityBoundaryGhost(int mInitial, int m, int nInitial, int n, double InletSideUz, double InletSideUx, double InletSideUy, double solid, double gasCritical);
extern void HeightFirstConstantPressureBoundaryGhost(int mInitial, int m, int nInitial, int n, double InletDensity, double InletSideUx, double InletSideUy, double solid, double gasCritical);
extern void HeightLastConstantPressureBoundaryGhost(int q, int mInitial, int m, int nInitial, int n, double outPutDensity, double InletSideUx, double InletSideUy, double solid, double gasCritical);
extern void HeightFirstDirichletConcentration(int Length,int Width,double InletConcentration,double gasCritical,double constant);
extern void HeightFirstDirichletConcentrationD3Q7(int Length,int Width,double InletConcentration,double gasCritical,double constant);
extern void HeightLastDirichletConcentrationD3Q7(int Length, int Width, double InletConcentration, double gasCritical, int constant);
extern void WidthLastDirichletConcentrationD3Q7(int Length, int initialHeight, int Height, double InletConcentration, double gasCritical, int constant);
extern void WidthLastDirichletConcentrationFirstD3Q7(int Length, int initialHeight, int Height, double InletConcentration, double gasCritical, int constant);
extern void HeightFirstDirichletConcentrationFirst(int Length,int Width,double InletConcentration,double gasCritical,double constant);
extern void HeightFirstDirichletConcentrationFirstD3Q7(int Length,int Width,double InletConcentration,double gasCritical,double constant);
extern void HeightLastDirichletConcentrationFirstD3Q7(int Length, int Width, double InletConcentration, double gasCritical, int constant);
extern void HeightFirstDirichletConcentrationSecond(int Length,int Width,double InletConcentration,double gasCritical,double constant);
extern void HeightFirstDirichletConcentrationSecondD3Q7(int Length,int Width,double InletConcentration,double gasCritical,double constant);
extern void HeightLastDirichletConcentrationSecondD3Q7(int Length, int Width, double InletConcentration, double gasCritical, int constant);
extern void HeightLastDirichletConcentration(int q,int Length,int Width,double OutletConcentration,double gasCritical);
extern void HeightLastNeumannConcentration(int Length,int Width,int Height);
extern void HeightLastNeumannConcentrationD3Q7(int Length,int Width,int Height);
extern void WidthLastNeumannConcentrationD3Q7(int Length, int Width, int initialHeight, int Height);
extern void WidthLastNeumannConcentrationFirstD3Q7(int Length, int Width, int initialHeight, int Height);
extern void HeightFirstNeumannConcentrationD3Q7(int Length, int Width, int Height);
extern void HeightLastNeumannConcentrationFirst(int Length,int Width,int Height);
extern void HeightLastNeumannConcentrationFirstD3Q7(int Length,int Width,int Height);
extern void HeightFirstNeumannConcentrationFirstD3Q7(int Length, int Width, int Height);
extern void HeightLastNeumannConcentrationSecond(int Length,int Width,int Height);
extern void HeightLastNeumannConcentrationSecondD3Q7(int Length,int Width,int Height);
extern void widthFirstNeumannElectrodePotential(int Length,int Width,int Height);
extern void widthFirstNeumannElectrodePotentialD3Q7(int Length,int Width,int Height);
extern void widthFirstDirichletElectrodePotentialD3Q7(int Length,int Width,int Height, double InletElectrodePotential);
extern void lengthFirstNeumannElectrodePotential(int Length,int Width,int Height);
extern void lengthFirstNeumannElectrodePotentialD3Q7(int Length,int Width,int Height);
extern void lengthLastNeumannElectrodePotential(int Length,int Width,int Height);
extern void lengthLastNeumannElectrodePotentialD3Q7(int Length,int Width,int Height);
extern void HeightFirstNeumannElectrodePotential(int Length,int Width,int Height);
extern void HeightFirstNeumannElectrodePotentialD3Q7(int Length,int Width,int Height);
extern void HeightLastNeumannElectrodePotential(int Length,int Width,int Height);
extern void HeightLastNeumannElectrodePotentialD3Q7(int Length,int Width,int Height);
extern void widthLastDirichletelectrodePotential(int Length,int Width, int Height,double constant);
extern void widthLastDirichletelectrodePotentialD3Q7(int Length,int Width, int Initial, int Height,double constant);
extern void widthLastNeumannelectrodePotentialD3Q7(int Length, int Width, int Initial, int Height);
extern void widthLastNeumannelectrolytePotentialD3Q7(int Length, int Width, int Initial, int Height);
extern void HeightFirstNeumannElectrolytePotential(int Length,int Width,int Height);
extern void HeightFirstNeumannElectrolytePotentialD3Q7(int Length,int Width,int Height);
extern void HeightLastNeumannElectrolytePotential(int Length,int Width,int Height);
extern void HeightLastNeumannElectrolytePotentialD3Q7(int Length,int Width,int Height);
extern void widthFirstNeumannElectrolytePotential(int Length,int Width,int Height);
extern void widthFirstDirichletElectrolytePotentialD3Q7(int Length,int Width,int Height, double InletElectrolytePotential, double gasCritical);
extern void widthFirstConstantCurrentElectrolytePotentialD3Q7(int Length,int Width,int Initial,int Height, double constant, double gasCritical);
extern void widthFirstConstantCurrentConcentrationD3Q7(int Length, int Width, int Initial, int Height, double constant, double gasCritical, double transferenceNumber);
extern void widthLastElectrodeConcentrationNeumannD3Q7(int Length, int Width, int Height);
extern void lengthFirstNeumannElectrolytePotentialD3Q7(int Length,int Width,int Height);
extern void lengthLastNeumannElectrolytePotentialD3Q7(int Length,int Width,int Height);
extern void lengthFirstNeumannConcentrationD3Q7(int Length,int Width,int Height);
extern void lengthLastNeumannConcentrationD3Q7(int Length,int Width,int Height);
extern void lengthFirstNeumannConcentrationFirstD3Q7(int Length,int Width,int Height);
extern void lengthLastNeumannConcentrationFirstD3Q7(int Length,int Width,int Height);
extern void lengthFirstNeumannConcentrationSecondD3Q7(int Length,int Width,int Height);
extern void lengthLastNeumannConcentrationSecondD3Q7(int Length,int Width,int Height);

#endif