#ifndef _CONCENTRATIONFIELD_H
#define _CONCENTRATIONFIELD_H

extern double ***cIn0;
extern double ***cIn1;
extern double ***cIn2;
extern double ***cIn3;
extern double ***cIn4;
extern double ***cIn5;
extern double ***cIn6;
extern double ***cIn7;
extern double ***cIn8;
extern double ***cIn9;
extern double ***cIn10;
extern double ***cIn11;
extern double ***cIn12;
extern double ***cIn13;
extern double ***cIn14;
extern double ***cIn15;
extern double ***cIn16;
extern double ***cIn17;
extern double ***cIn18;
extern double ***Concentration;
extern double ***domainConnection;
extern double ***wallNearConcentration;
extern double ***wallNearConcentrationFirst;
extern double ***convectTermConcentration;
extern double ***diffusionTermConcentration;
extern double ***reactantSurface1;
extern double ***reactantSurface2;
extern double ***reactantSurface3;
extern double ***reactantSurface4;
extern double ***reactantSurface5;
extern double ***reactantSurface6;
extern double ***massTransCoeMatrix;
extern double ***electrolyteConcentrationRelaxationTime;

extern double ***cIn0First;
extern double ***cIn1First;
extern double ***cIn2First;
extern double ***cIn3First;
extern double ***cIn4First;
extern double ***cIn5First;
extern double ***cIn6First;
extern double ***cIn7First;
extern double ***cIn8First; 
extern double ***cIn9First;
extern double ***cIn10First;
extern double ***cIn11First;
extern double ***cIn12First;
extern double ***cIn13First;
extern double ***cIn14First;
extern double ***cIn15First;
extern double ***cIn16First;
extern double ***cIn17First;
extern double ***cIn18First;
extern double ***ConcentrationFirst;
extern double ***convectTermConcentrationFirst;
extern double ***diffusionTermConcentrationFirst;

extern double ***cIn0Second;
extern double ***cIn1Second;
extern double ***cIn2Second;
extern double ***cIn3Second;
extern double ***cIn4Second;
extern double ***cIn5Second;
extern double ***cIn6Second;
extern double ***cIn7Second;
extern double ***cIn8Second;
extern double ***cIn9Second;
extern double ***cIn10Second;
extern double ***cIn11Second;
extern double ***cIn12Second;
extern double ***cIn13Second;
extern double ***cIn14Second;
extern double ***cIn15Second;
extern double ***cIn16Second;
extern double ***cIn17Second;
extern double ***cIn18Second;
extern double ***ConcentrationSecond;
extern double ***convectTermConcentrationSecond;
/*****************************************************************************************************************/
extern void FieldArrangeConcentration(int Length, int Width, int Height);
extern void FieldArrangeConcentrationFirst(int Length, int Width, int Height);
extern void FieldArrangeConcentrationSecond(int Length, int Width, int Height);
extern void domainConnectionRegion(int Length, int Width, int Height, double gasCritical);
extern void domainConnectionRegionD3Q7(int Length, int Width, int Height, double gasCritical);
extern void FieldInitialConcentration(int Length, int Width, int Height, double ConcentrationInitial, double gasCritical, double ***ux, double ***uy, double ***uz);
extern void FieldInitialConcentrationElectrolyteD3Q7(int Length, int Width, int Height, double ConcentrationInitial, double gasCritical);
extern void FieldInitialConcentrationD3Q15(int Length, int Width, int Height, double ConcentrationInitial, double gasCritical, double ***ux, double ***uy, double ***uz);
extern void FieldInitialConcentrationFirst(int Length, int Width, int Height, double ConcentrationInitial, double gasCritical, double ***ux, double ***uy, double ***uz);
extern void FieldInitialConcentrationElectrodeD3Q7(int Length, int Width, int Height, double ConcentrationInitial, double gasCritical);
extern void FieldInitialConcentrationSecond(int Length, int Width, int Height, double ConcentrationInitial, double gasCritical, double ***ux, double ***uy, double ***uz);
extern void FieldInitialConcentrationSecondD3Q7(int Length, int Width, int Height, double ConcentrationInitial, double gasCritical);
extern void FieldInitialReactantSurface(int Length, int Width, int Height);
extern void CollisionSRTConcentration(int Length, int Width, int Height, double CrelaxationTime, double gasCritical);
extern void CollisionMRTConcentrationD3Q7(int Length, int Width, int Height, double gasCritical, double ***Ux, double ***Uy, double ***Uz, double a);
extern void CollisionMRTConcentrationD3Q15(int Length, int Width, int Height, double gasCritical, double ***Ux, double ***Uy, double ***Uz, double alpha1, double alpha2);
extern void electrolyteConcentrationRelaxationTimeCalculation(int Length, int Width, int Height, double constant, double gasCritical,double constantMol,double constant1);
extern void CollisionSRTConcentrationD3Q7(int Length, int Width, int Height, double gasCritical);
extern void CollisionSRTConcentrationFirst(int Length,int Width,int Height,double CrelaxationTime,double gasCritical);
extern void CollisionSRTConcentrationElectrodeD3Q7(int Length, int Width, int Height, double CrelaxationTime, double gasCritical);
extern void CollisionMRTConcentrationElectrodeD3Q7(int Length, int Width, int Height);
extern void CollisionSRTConcentrationSecond(int Length,int Width,int Height,double CrelaxationTime,double gasCritical);
extern void CollisionSRTConcentrationSecondD3Q7(int Length, int Width, int Height, double CrelaxationTime, double gasCritical);
extern void MemoryFreeConcentration(int m, int n, int q);
extern void MemoryFreeConcentrationFirst(int m, int n, int q);
extern void MemoryFreeConcentrationSecond(int m, int n, int q);
extern void StreamConcentration(int m, int n, int q);
extern void StreamConcentrationD3Q7(int m, int n, int q);
extern void StreamConcentrationD3Q15(int m, int n, int q);
extern void StreamConcentrationFirst(int m, int n, int q);
extern void StreamConcentrationElectrodeD3Q7(int m, int n, int q);
extern void StreamConcentrationSecond(int m, int n, int q);
extern void StreamConcentrationSecondD3Q7(int m, int n, int q);
extern void FieldCalculationConcentration(int m, int n, int q, double gasCritical);
extern void FieldCalculationConcentrationD3Q7(int m, int n, int q, double gasCritical);
extern void FieldCalculationConcentrationD3Q15(int m, int n, int q, double gasCritical);
extern void FieldCalculationConcentrationFirst(int m, int n, int q, double gasCritical);
extern void FieldCalculationConcentrationElectrodeD3Q7(int m, int n, int q, double gasCritical);
extern void FieldCalculationConcentrationSecond(int m, int n, int q, double gasCritical);
extern void FieldCalculationConcentrationSecondD3Q7(int m, int n, int q, double gasCritical);
extern void reactionConcentrationD3Q7(int m, int n, int q, double gasCritical, double latticeF, double transferenceNumber, double constant);
extern void reactionConcentrationElectrodeD3Q7(int m, int n, int q, double gasCritical, double latticeF, double constant);
extern void reactionConcentrationSecondD3Q7(int m, int n, int q, double gasCritical,double RateConstant,double equilibriumPotential,double K,double exchange);
extern void refillConcentration(int m, int n, int q, double gasCritical,double ***rho1, double ***rho2, double ***ux, double ***uy, double ***uz);
extern void lastConcentration(int Length, int Width, int Height, double gasCritical);
extern void additionalTermCalculationConcentrationD3Q7(int Length, int Width, int Height, double gasCritical, double ***Ux, double ***Uy, double ***Uz, double constant);
extern void additionalTermCalculationConcentrationFirstD3Q7(int Length, int Width, int Height, double gasCritical, double ***Ux, double ***Uy, double ***Uz, double constant);
extern void additionalTermCalculationConcentrationSecondD3Q7(int Length, int Width, int Height, double gasCritical, double ***Ux, double ***Uy, double ***Uz, double constant);
extern void additionalDiffusionTermCalculationD3Q7(int Length, int Width, int Height, double constant1, double constant2, double gasCritical);
extern void massTransMatrix(int Length, int Width, int Height, double a, double b);

#endif