#ifndef _CONTINUE_H
#define _CONTINUE_H

extern FILE *InitialDomain;

extern FILE *InitialRho;
extern FILE *InitialUx;
extern FILE *InitialUy;
extern FILE *InitialUz;
extern FILE *InitialPressure;
extern FILE *InitialFIn0;
extern FILE *InitialFIn1;
extern FILE *InitialFIn2;
extern FILE *InitialFIn3;
extern FILE *InitialFIn4;
extern FILE *InitialFIn5;
extern FILE *InitialFIn6;
extern FILE *InitialFIn7;
extern FILE *InitialFIn8;
extern FILE *InitialFIn9;
extern FILE *InitialFIn10;
extern FILE *InitialFIn11;
extern FILE *InitialFIn12;
extern FILE *InitialFIn13;
extern FILE *InitialFIn14;
extern FILE *InitialFIn15;
extern FILE *InitialFIn16;
extern FILE *InitialFIn17;
extern FILE *InitialFIn18;

extern FILE *InitialReactantSurface1;
extern FILE *InitialReactantSurface2;
extern FILE *InitialReactantSurface3;
extern FILE *InitialReactantSurface4;
extern FILE *InitialReactantSurface5;
extern FILE *InitialReactantSurface6;

extern FILE *InitialConcentration;
extern FILE *InitialCIn0;
extern FILE *InitialCIn1;
extern FILE *InitialCIn2;
extern FILE *InitialCIn3;
extern FILE *InitialCIn4;
extern FILE *InitialCIn5;
extern FILE *InitialCIn6;
extern FILE *InitialCIn7;
extern FILE *InitialCIn8;
extern FILE *InitialCIn9;
extern FILE *InitialCIn10;
extern FILE *InitialCIn11;
extern FILE *InitialCIn12;
extern FILE *InitialCIn13;
extern FILE *InitialCIn14;
extern FILE *InitialCIn15;
extern FILE *InitialCIn16;
extern FILE *InitialCIn17;
extern FILE *InitialCIn18;

extern FILE *InitialConcentrationFirst;
extern FILE *InitialCIn0First;
extern FILE *InitialCIn1First;
extern FILE *InitialCIn2First;
extern FILE *InitialCIn3First;
extern FILE *InitialCIn4First;
extern FILE *InitialCIn5First;
extern FILE *InitialCIn6First;
extern FILE *InitialCIn7First;
extern FILE *InitialCIn8First;
extern FILE *InitialCIn9First;
extern FILE *InitialCIn10First;
extern FILE *InitialCIn11First;
extern FILE *InitialCIn12First;
extern FILE *InitialCIn13First;
extern FILE *InitialCIn14First;
extern FILE *InitialCIn15First;
extern FILE *InitialCIn16First;
extern FILE *InitialCIn17First;
extern FILE *InitialCIn18First;

extern FILE *InitialConcentrationSecond;
extern FILE *InitialCIn0Second;
extern FILE *InitialCIn1Second;
extern FILE *InitialCIn2Second;
extern FILE *InitialCIn3Second;
extern FILE *InitialCIn4Second;
extern FILE *InitialCIn5Second;
extern FILE *InitialCIn6Second;
extern FILE *InitialCIn7Second;
extern FILE *InitialCIn8Second;
extern FILE *InitialCIn9Second;
extern FILE *InitialCIn10Second;
extern FILE *InitialCIn11Second;
extern FILE *InitialCIn12Second;
extern FILE *InitialCIn13Second;
extern FILE *InitialCIn14Second;
extern FILE *InitialCIn15Second;
extern FILE *InitialCIn16Second;
extern FILE *InitialCIn17Second;
extern FILE *InitialCIn18Second;

extern FILE *InitialRhoGhost;
extern FILE *InitialUxGhost;
extern FILE *InitialUyGhost;
extern FILE *InitialUzGhost;
extern FILE *InitialFIn0Ghost;
extern FILE *InitialFIn1Ghost;
extern FILE *InitialFIn2Ghost;
extern FILE *InitialFIn3Ghost;
extern FILE *InitialFIn4Ghost;
extern FILE *InitialFIn5Ghost;
extern FILE *InitialFIn6Ghost;
extern FILE *InitialFIn7Ghost;
extern FILE *InitialFIn8Ghost;
extern FILE *InitialFIn9Ghost;
extern FILE *InitialFIn10Ghost;
extern FILE *InitialFIn11Ghost;
extern FILE *InitialFIn12Ghost;
extern FILE *InitialFIn13Ghost;
extern FILE *InitialFIn14Ghost;
extern FILE *InitialFIn15Ghost;
extern FILE *InitialFIn16Ghost;
extern FILE *InitialFIn17Ghost;
extern FILE *InitialFIn18Ghost;

extern FILE *InitialElectrodePotential;
extern FILE *InitialElectrodeIn0;
extern FILE *InitialElectrodeIn1;
extern FILE *InitialElectrodeIn2;
extern FILE *InitialElectrodeIn3;
extern FILE *InitialElectrodeIn4;
extern FILE *InitialElectrodeIn5;
extern FILE *InitialElectrodeIn6;
extern FILE *InitialElectrodeIn7;
extern FILE *InitialElectrodeIn8;
extern FILE *InitialElectrodeIn9;
extern FILE *InitialElectrodeIn10;
extern FILE *InitialElectrodeIn11;
extern FILE *InitialElectrodeIn12;
extern FILE *InitialElectrodeIn13;
extern FILE *InitialElectrodeIn14;
extern FILE *InitialElectrodeIn15;
extern FILE *InitialElectrodeIn16;
extern FILE *InitialElectrodeIn17;
extern FILE *InitialElectrodeIn18;

extern FILE *InitialElectrolytePotential;
extern FILE *InitialElectrolyteIn0;
extern FILE *InitialElectrolyteIn1;
extern FILE *InitialElectrolyteIn2;
extern FILE *InitialElectrolyteIn3;
extern FILE *InitialElectrolyteIn4;
extern FILE *InitialElectrolyteIn5;
extern FILE *InitialElectrolyteIn6;
extern FILE *InitialElectrolyteIn7;
extern FILE *InitialElectrolyteIn8;
extern FILE *InitialElectrolyteIn9;
extern FILE *InitialElectrolyteIn10;
extern FILE *InitialElectrolyteIn11;
extern FILE *InitialElectrolyteIn12;
extern FILE *InitialElectrolyteIn13;
extern FILE *InitialElectrolyteIn14;
extern FILE *InitialElectrolyteIn15;
extern FILE *InitialElectrolyteIn16;
extern FILE *InitialElectrolyteIn17;
extern FILE *InitialElectrolyteIn18;

extern void fileAdressDomain();
extern void fileAddressTwoPhase();
extern void fileAddressReactantSurface();
extern void fileAddressConcentration();
extern void fileAddressConcentrationFirst();
extern void fileAddressConcentrationSecond();
extern void fileAddressVelocityGhost();
extern void fileAddressElectrodePotential();
extern void fileAddressElectrolytePotential();
extern void ContinueLoadDomain(int m, int n, int q);
extern void ContinueLoadTwoPhase(int m, int n, int q);
extern void ContinueLoadReactantSurface(int m, int n, int q);
extern void ContinueLoadConcentration(int m, int n, int q);
extern void ContinueLoadConcentrationFirst(int m, int n, int q);
extern void ContinueLoadConcentrationSecond(int m, int n, int q);
extern void ContinueLoadVelocityGhost(int m, int n, int q);
extern void ContinueLoadElectrodePotential(int m, int n, int q);
extern void ContinueLoadElectrolytePotential(int m, int n, int q);

#endif